config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :team_members, controllers: { registrations: 'team_members/registrations' }
  # devise_for :companies
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'home#index'
  resources :departments do
    resources :desingations
  end
  resources :companies do
    resources :permissions, only: %w[index] do
      collection do
        post 'permissions_setter'
      end
    end
  end

  resources :applicants do
    collection do
      get "applicant_profile_data"
    end
    resources :interviews
  end
  resources :team_members
  resources :comments
  resources :profiles
  resources :roles
  resources :subscriptions
  resources :organisation_settings,only:[:index,:new,:edit]
  
  get '/team_members/:id/interviews' => 'interviews#interview_feedback', as: "interview_feedback"

  put 'team_members/:id/feedback_update' => 'interviews#feedback_update', as: 'feedback_update'

  get '/team_members/:id/assigned_interviews' => 'interviews#assigned_interviews', as: 'assigned_interviews'
  get '/interviews/data' =>'interviews#data'
  get '/interviews/show_data' =>'interviews#show_data'
  post '/team_members_create' => 'team_members#create_member', as: 'create_team_member'
  delete '/team_members/:id' => 'team_members#destroy', as: 'delete_member'

  resources :bulk_uploads, only: %w[index new create]

  get '/team_details/' => 'team_members#team_details', as: 'team_details'

  get '/applicant_upload_bulk/new' => 'applicants#new_bulk_upload', as: 'bulk_upload_applicant'
  post '/applicant_upload_bulk/new' => 'bulk_uploads#create'
  post '/applicant_upload_bulk/data' => 'applicants#applicant_data_mapping', as: 'bulk_upload_data'
  post '/applicant_upload_bulk/rejected' => 'applicants#send_csv'
  get  "/saml/init" => "saml#init"
  post "/saml/consume" => "saml#consume"
  post "/saml/create_sso_organization" => "saml#create_sso_organization"
  post "/saml/create_user" => "saml#create_user"
  get  "sign-in" => "saml#sign", as: :saml_sign
  delete  "saml/logout" => "saml#logout"
  post '/create_organisation' =>'organisation_settings#create_organisation'
  get '/home/graph_show' => 'home#graph_show'
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :authenticate_team_member!
  before_action :require_company!
  before_action :load_applicant!, except: %w[assigned_interviews interview_feedback feedback_update data show_data ] 
  before_action :load_resource, only: %w[show edit update destroy]
  before_action :load_team_resource, only: %w[interview_feedback feedback_update]
  # before_action :auth_interview, except: %w(index new create assigned_interviews interview_feedback feedback_update)
  before_action :authorize_section, only: %i[index show new create edit update destroy]

  def index
    @interviews = @applicant.interviews
  end

  def assigned_interviews
    @interviews = current_team_member.interviews
  end

  def show; end

  def interview_feedback; end

  def feedback_update
    if @interview.update(interview_params)
      respond_to do |format|
        format.html { redirect_to assigned_interviews_path, notice: 'Inteview Feedback Submitted!' }
      end
    else
      redirect_to root_path
    end
  end

  def new
    @interview = @applicant.interviews.new
    @interview.comments.build
  end

  def create
    @interview = @applicant.interviews.new(interview_params)
    if @interview.save
      redirect_to applicant_path(@applicant.id), notice: 'Inteview scheduled successfully!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @interview.update(interview_params)
      redirect_to applicant_path(@applicant.id), notice: 'Interview details updated.'
    else
      render :edit
    end
  end

  def data
  start_date = Time.now
  end_date = 7.days.from_now
  applicants = current_company.applicants
  interviews_data = Interview.joins(:applicant)
                    .where(applicants: { company_id: current_company.id }, interview_date: start_date..end_date)
                    .group("DATE(interview_date)")
                    .count
  date_range = (start_date.to_date...end_date.to_date).map { |date| date.strftime("%d-%b") }
  default_data = Hash[date_range.product([nil])]
  final_data = default_data.merge(interviews_data.transform_keys { |key| key.strftime("%d-%b") })
  render json: final_data
end

  def show_data
  start_date = 1.month.ago
  end_date = Time.now
  applicants = current_company.applicants
  interviews_data = Interview.joins(:applicant)
                    .where(applicants: { company_id: current_company.id }, interview_date: start_date..end_date)
                    .group("DATE(interview_date)")
                    .count
  date_range = (start_date.to_date...end_date.to_date).map { |date| date.strftime("%d-%b") }
  default_data = Hash[date_range.product([nil])]
  final_data = default_data.merge(interviews_data.transform_keys { |key| key.strftime("%d-%b") })
  render json: final_data
end

  private

  def authorize_section
    authorize :Interview
  end

  def interview_params
    params.require(:interview).permit(:title, :team_member_id, :applicant_id, :interview_date, :status,
                                      comments_attributes: %i[id content commentable_id commentable_type team_member_id])
  end

  def load_resource
    @interview = @applicant.interviews.find(params[:id])
  end

  def load_applicant!
    @applicant = current_company.applicants.find(params[:applicant_id])
  end

  def load_team_resource
    @interview = current_team_member.interviews.find(params[:id])
  end

  # def auth_interview
  #   authorize @interview
  # end
end

app/views/interviews/_form.html.erb
<div class="page-wrapper">
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Schedule Interview</h3>
        </div>

        <%= form_with(model: @interview, url: applicant_interviews_path(@applicant, @interview), local: true, class: "card",data: { turbo: false }) do |f| %>
        <div class="card-body">
          <div class="row row-cards">
            <%@interview.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :title, class: "form-label" %>
                <%= f.text_field :title, :placeholder => "Enter Interview Title" , class: "form-control"%> 
              </div>
            </div>
            <%@interview.errors.full_messages_for(:interview_date).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :interview_date, class: "form-label" %>
                <%= f.datetime_field :interview_date, :placeholder => "Enter Schedule Date" , class: "form-control" , ampm: true , :prefix => :start_date%> 
              </div>
            </div>
            <%@interview.errors.full_messages_for(:status).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :status, class: "form-label" %>
                <%= f.select :status, options_for_select(Interview.statuses.keys), { prompt: 'Select a status' }, class: 'form-control', id: 'role-dropdown' %>
              </div>
            </div>
            <%@interview.errors.full_messages_for(:team_member_id).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :team_member_id, value: "Select Team member", class: "form-label" %>
                <%= f.select :team_member_id, options_from_collection_for_select(current_company.team_members.all, :id, :name), { prompt: 'Select a team member' }, class: 'form-control', id: 'team-member-dropdown' %>

              </div>                                        
            </div>

            <div class="col-md-5">
              <div class="mb-3">
                <%= f.fields_for :comments do |comment_form| %>
                  <%= comment_form.label :content,value: "comment", class: "form-label" %>
                  <%= comment_form.text_field :content, class: "form-control", placeholder: "comment" %>
                  <%= comment_form.hidden_field :team_member_id, value: current_team_member.id %>
                <% end %>
              </div>
            </div>

          </div>
        </div>

        <div class="card-footer text-end">    
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/interviews/_interview_feedback.html.erb
<%= form_with model: @interview, url: feedback_update_path, method: :put do |f| %>
  <div class="card-body">
    <div class="row row-cards">
      <div class="col-md-12">
        <div class="mb-3">
          <%= f.label :status, class: "form-label" %>
          <%= f.select(:status, Interview.statuses.keys, {}, class: "form-control") %>                  
        </div>
      </div> 
    </div>
    <div class="col-md-12">
      <%= f.fields_for :comments, @interview.comments.new do |ff| %>
        <div class="mb-3">
          <%= ff.label :content, value: "comment", class: "form-label" %>
          <%= ff.text_area :content, class: "form-control", placeholder: "comment" %>
          <%= ff.hidden_field :team_member_id, value: current_team_member.id %>
        </div>
      <% end %>  
    </div>
  </div>
  <div class="card-footer text-end">    
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/interviews/_modal_popup.html.erb
<div class="modal" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Feedback</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="feedback_modal">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/interviews/assigned_interviews.html.erb
<%= render partial: "modal_popup" %>

<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Assigned Interviews</h1> 
  </div>

  <% if current_team_member.interviews.present? %>
    <div class="table-responsive shadow">
      <table class="table table-bordered table-go">
        <thead>
          <tr>
            <th>Title</th>
            <th>Interviewer</th>
            <th>Applicant Name</th>
            <th>Status</th>
            <th>Interview Date</th>
            <th>Comment</th>
            <th>Action</th>                                                      
          </tr>
        </thead>
        <tbody class="table-tbody">
          <% @interviews.each do |interview| %>
          <tr>
            <td class="sort-name"><%= interview.title %></td>
            <td class="sort-name"><%= interview.team_member.name %></td>
            <td class="sort-name"><%= Applicant.find(interview.applicant_id).name %></td>
            <td class="sort-name"><div class="<%= interview.status_color %>"><%= interview.status %></div></td>
            <td class="sort-name"><%= interview.interview_date.strftime("%d-%m-%Y %I:%M %p") %></td>
            <td class="sort-name"><%= interview.comments.pluck(:content).join(" ")%></td>

            <td class="actions">
              <% if policy(:Interview).create? %>
                <%= link_to interview_feedback_path(interview), remote: true do %>
                  <i class="fa fa-comments"></i>
                <% end %>
              <% end %>
            </td>                      
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% elsif current_team_member.interviews.blank? %>
    No Interview Assigned!
  <% end %>
</div>

app/views/interviews/edit.html.erb
<div class="page-wrapper">
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Edit Interview</h3>
        </div>

        <%= form_with(model: @interview, url: applicant_interview_path(@applicant, @interview),method: :patch,local: true, class: "card",data: { turbo: false }) do |f| %>
          <div class="card-body">
            <div class="row row-cards">
              <%@interview.errors.full_messages_for(:title).each do |message| %>
              <div><%= message %></div>
              <%end%>
              <div class="col-md-5">
                <div class="mb-3">
                  <%= f.label :title, class: "form-label" %>
                  <%= f.text_field :title, :placeholder => "Enter Interview Title" , class: "form-control"%> 
                </div>
              </div>
              <%@interview.errors.full_messages_for(:interview_date).each do |message| %>
              <div><%= message %></div>
              <%end%>
              <div class="col-md-5">
                <div class="mb-3">
                  <%= f.label :interview_date, class: "form-label" %>
                  <%= f.datetime_field :interview_date, :placeholder => "Enter Schedule Date" , class: "form-control" , ampm: true , :prefix => :start_date%> 
                </div>
              </div>
              <%@interview.errors.full_messages_for(:status).each do |message| %>
              <div><%= message %></div>
              <%end%>
              <div class="col-md-5">
                <div class="mb-3">
                  <%= f.label :status, class: "form-label" %>
                  <%= f.select :status, options_for_select(Interview.statuses.keys), { prompt: 'Select a status' }, class: 'form-control', id: 'role-dropdown' %>
                </div>
              </div>
              <%@interview.errors.full_messages_for(:team_member_id).each do |message| %>
              <div><%= message %></div>
              <%end%>
              <div class="col-md-5">
                <div class="mb-3">
                  <%= f.label :team_member_id, value: "Select Team member", class: "form-label" %>
                  <%= f.select :team_member_id, options_from_collection_for_select(current_company.team_members.all, :id, :name), { prompt: 'Select a team member' }, class: 'form-control', id: 'team-member-dropdown' %>
                </div>                                        
              </div>

              <div class="col-md-5">
                <div class="mb-3">
                  <%= f.fields_for :comments do |comment_form| %>
                    <%= comment_form.label :content,value: "comment", class: "form-label" %>
                    <%= comment_form.text_field :content, class: "form-control", placeholder: "comment" %>
                    <%= comment_form.hidden_field :team_member_id, value: current_team_member.id %>
                  <% end %>
                </div>
              </div>

            </div>
          </div>

          <div class="card-footer text-end">    
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/interviews/index.html.erb
</table>
<div class="page-wrapper">
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <h2 class="page-title">
            Interviews
          </h2>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
        </div>
      </div>
    </div>
  </div>
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-body">
          <div id="table-default" class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><button>Title</button></th>
                  <th><button>Interviewer</button></th>
                  <th><button>Applicant Name</button></th>
                  <th><button>Status</button></th>
                  <th><button>Interview Date</button></th>
                  <th><button>Comment</button></th>                                                      
                </tr>
              </thead>
              <tbody class="table-tbody">
                <% @interviews.each do |interview| %>
                <tr>
                  <td class="sort-name"><%= interview.title %></td>
                  <td class="sort-name"><%= TeamMember.find(interview.team_member_id).name %></td>
                  <td class="sort-name"><%= Applicant.find(interview.applicant_id).name %></td>
                  <td class="sort-name"><%= interview.status %></td>
                  <td class="sort-name"><%= interview.interview_date.strftime("%d-%m-%Y %I:%M %p") %></td>
                  <td class="sort-name"><%= interview.comments.pluck(:content).join(" ")%></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/interviews/interview_feedback.js.erb
$("#feedback_modal").html("<%= escape_javascript(render 'interview_feedback') %>");
$("#myModal").modal("show");

app/views/interviews/new.html.erb
<%= render partial: "form" %>

app/views/interviews/show.html.erb
<div class="page-wrapper">
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <h2 class="page-title">
            Interview Details
          </h2>
        </div>
      </div>
    </div>
  </div>
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Interview info</h3>
          <div class="col-auto ms-auto d-print-none">
            <div class="btn-list">
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="datagrid">
            <div class="datagrid-item">
              <div class="datagrid-title">Title</div>
              <div class="datagrid-content"><%= @interview.title %></div>
            </div>
            <div class="datagrid-item">
              <div class="datagrid-title">Team member id</div>
              <div class="datagrid-content"><%= @interview.team_member_id %></div>
            </div>
            <div class="datagrid-item">
              <div class="datagrid-title">Applicant id</div>
              <div class="datagrid-content"><%= @interview.applicant_id %></div>
            </div>
            <div class="datagrid-item">
              <div class="datagrid-title">Interview Date</div>
              <div class="datagrid-content"><%= @interview.interview_date %></div>
            </div>
            
            <div class="datagrid-item">
              <div class="datagrid-title <%= interview.status_color %>">status</div>
              <div class="datagrid-content"><%= @interview.status%></div>
            </div>
          </div>
        </div>                   
      </div>
    </div>
  </div>
</div>