config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :team_members, controllers: { registrations: 'team_members/registrations' }
  # devise_for :companies
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'home#index'
  resources :departments do
    resources :desingations
  end
  resources :companies do
    resources :permissions, only: %w[index] do
      collection do
        post 'permissions_setter'
      end
    end
  end

  resources :applicants do
    collection do
      get "applicant_profile_data"
    end
    resources :interviews
  end
  resources :team_members
  resources :comments
  resources :profiles
  resources :roles
  resources :subscriptions
  resources :organisation_settings,only:[:index,:new,:edit]
  
  get '/team_members/:id/interviews' => 'interviews#interview_feedback', as: "interview_feedback"

  put 'team_members/:id/feedback_update' => 'interviews#feedback_update', as: 'feedback_update'

  get '/team_members/:id/assigned_interviews' => 'interviews#assigned_interviews', as: 'assigned_interviews'
  get '/interviews/data' =>'interviews#data'
  get '/interviews/show_data' =>'interviews#show_data'
  post '/team_members_create' => 'team_members#create_member', as: 'create_team_member'
  delete '/team_members/:id' => 'team_members#destroy', as: 'delete_member'

  resources :bulk_uploads, only: %w[index new create]

  get '/team_details/' => 'team_members#team_details', as: 'team_details'

  get '/applicant_upload_bulk/new' => 'applicants#new_bulk_upload', as: 'bulk_upload_applicant'
  post '/applicant_upload_bulk/new' => 'bulk_uploads#create'
  post '/applicant_upload_bulk/data' => 'applicants#applicant_data_mapping', as: 'bulk_upload_data'
  post '/applicant_upload_bulk/rejected' => 'applicants#send_csv'
  get  "/saml/init" => "saml#init"
  post "/saml/consume" => "saml#consume"
  post "/saml/create_sso_organization" => "saml#create_sso_organization"
  post "/saml/create_user" => "saml#create_user"
  get  "sign-in" => "saml#sign", as: :saml_sign
  delete  "saml/logout" => "saml#logout"
  post '/create_organisation' =>'organisation_settings#create_organisation'
  get '/home/graph_show' => 'home#graph_show'
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  has_many :interviews, dependent: :destroy
  devise  :database_authenticatable,:registerable,
  :recoverable, :rememberable
  #validates :password ,presence:false
  belongs_to :company, inverse_of: :team_members
  belongs_to :role
  has_many :bulk_uploads 
  accepts_nested_attributes_for :company
  has_many :comments, dependent: :destroy
  has_many :permissions, ->(team_member) { where("permissions.role_id = ?", team_member.role_id) }, through: :company
  after_create :admin_all_permission

  # validates :name, :employee_id , :role_id , :contact_number, presence: true
  # validates_uniqueness_of :employee_id, :contact_number, :case_sensitive => true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  def admin?
    self.role.name == "Admin"
  end

  def hr?
    self.role.name == "HR"
  end

  def moderator?
    self.role.name == "Moderator"
  end

  def admin_all_permission
    if !self.role.company_id? && !self.role.create_by?
      role_up = self.role
      role_up.update(company_id: self.company.id, create_by: self.name)
    end
    models_name = Permission.all_models
    if self.role.name == "Admin"
      models_name.each do |model|
        permission = Permission.create(company_id: self.company_id, role_id: self.role_id, model_title: model, read_p: true, create_p: true, delete_p: true, update_p: true)
        permission.save
      end
    end
  end

  def self.search(search, email, name, profile, employee_id)
    if search.present?
      result = where("name ILIKE ? or email ILIKE ? or profile ILIKE ? or cast(employee_id as text) ILIKE ? or cast(contact_number as text) ILIKE ?" , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")

      if search.present?
        result.where("email ILIKE ? and name ILIKE ? and profile ILIKE ? and cast(employee_id as text) ILIKE ?", "%#{email}%", "%#{name}%", "%#{profile}%", "%#{employee_id}%")
      end

    elsif email.present? or name.present? or profile.present? or employee_id.present?
      where("email ILIKE ? and name ILIKE ? and profile ILIKE ? and cast(employee_id as text) ILIKE ?" ,  "%#{email}%", "%#{name}%", "%#{profile}%", "%#{employee_id}%")
    else search.blank?
      all
    end
  end
end

app/controllers/team_members/confirmations_controller.rb
# frozen_string_literal: true

class TeamMembers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/team_members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class TeamMembers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/team_members/passwords_controller.rb
# frozen_string_literal: true

class TeamMembers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/team_members/registrations_controller.rb
# frozen_string_literal: true

class TeamMembers::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: [:new, :create]

  # POST /resource
  def create
    params[:team_member][:role_id] = Role.admin.first&.id
    super do |resource|
      unless resource.errors.empty?
        clean_up_passwords resource
        set_minimum_password_length
        render turbo_stream: turbo_stream.replace(
          "error_explanation",
          partial: "devise/shared/error_messages",
          locals: { resource: resource }
        )
        return
      end
    end
  end


  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/team_members/sessions_controller.rb
# frozen_string_literal: true

class TeamMembers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/team_members/unlocks_controller.rb
# frozen_string_literal: true

class TeamMembers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :authenticate_team_member!
  before_action :get_team_member, only: [:show, :edit, :update, :destroy]
  before_action :authorize_section, only: %i[index show new create edit update destroy]


  def index
    search = params[:search]
    email = params[:email]
    name = params[:name]
    profile = params[:profile]
    employee_id = params[:employee_id]
    @company_members = current_team_member.company.team_members.search(search, email, name, profile, employee_id)
    @team_members = @company_members
  end

  def show
    if current_company.on_board?
      redirect_to edit_company_path(current_company.id)
    end
  end

  def new
    @team_member = TeamMember.new
    respond_to do |format|
      format.html
    end
  end

  def create
    # @team_member = TeamMember.new(team_member_params)
    # if @team_member.save
    #   redirect_to team_members_path, notice: "Employee registered"
    # else
    #   redirect_to new_team_member_path
    # end
  end


  def create_member
    @team_member = TeamMember.new(team_member_params)
    if @team_member.save
      redirect_to team_members_path, notice: "Employee registered"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @team_member.update(team_member_params)
      redirect_to team_members_path, notice: "Details Updated"
    else
      render :edit
    end
  end

  def destroy
    @team_member.destroy
    redirect_to team_members_path, notice: "Employee data removed!"
  end

  private

  def authorize_section
    authorize :TeamMember
  end

  def team_member_params
    params.require(:team_member).permit(:name, :employee_id, :email, :password, :contact_number, :role_id, :company_id, :profile, :search)
  end

  def get_team_member
    @team_member = TeamMember.find(params.fetch(:id))
  end
end

app/views/team_members/edit.html.erb
<div class="page-wrapper">
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">edit member</h3>
        </div>
        <%= form_for @team_member, local:true, url: @url, data: { turbo: false },class: "card" ,method: :patch do |f| %>
        <div class="card-body">
          <div class="row row-cards">
            <%@team_member.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, :placeholder => "Name" , class: "form-control"%> 
              </div>
            </div>              
  
            <%@team_member.errors.full_messages_for(:profile).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :profile, class: "form-label" %>
                <%= f.text_field :profile, :placeholder => "Profile", class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:employee_id).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :employee_id, class: "form-label" %>
                <%= f.text_field :employee_id, :placeholder => "employeeID" , class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:email).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :email, class: "form-label" %>
                <%= f.text_field :email, :placeholder => "email" , class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:role_id).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :role_id, class: "form-label" %>
                <%= f.text_field :role_id, :placeholder => "Role" , class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:contact_number).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :contact_number, class: "form-label" %>
                <%= f.text_field :contact_number, :placeholder => "contact number" , class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:password).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :password, class: "form-label" %>
                <%= f.password_field :password, :placeholder => "password" , class: "form-control" %> 
              </div>
            </div>              
          </div>
        </div> 
     

        
        <div class="card-footer text-end">    
          <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/team_members/index.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Team Members</h1>
    <% if policy(:TeamMember).create? %>
      <%= link_to new_team_member_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary btn-icon-split shadow-sm" do %>
        <span class="icon text-white-50">
          <i class="fas fa-user-plus fa-sm"></i>
        </span>
        <span class="text">New Team Member</span>
      <% end %>
    <% end %>
  </div>

  <div class="table-responsive shadow">
    <table class="table table-bordered table-go">
      <thead>
        <tr>
          <th>Employee ID</th>
          <th>Name</th>
          <th>Role</th>
          <th>Email</th>
          <th>contact number</th>
          <th>Profile</th>   
          <th>Action</th>              
        </tr>
      </thead>
      <tbody class="table-tbody">
        <% @team_members.each do |team_member| %>
        <tr>
          <td class="sort-designation_name"><%=team_member.employee_id%></td>
          <td class="sort-contact_number"><%=team_member.name%></td>
          <td class="sort-email"><%=team_member.role.name%></td>
          <td class="sort-location"><%=team_member.email%></td>
          <td class="sort-last_salary"><%=team_member.contact_number%></td>
          <td class="sort-last_salary"><%=team_member.profile%></td>

          <td class="actions">
            <% if policy(:TeamMember).read? %>
              <%= link_to team_member_path(team_member.id) do %>
                <i class="fa fa-eye"></i>
              <% end %>
            <% end %>

            <% if policy(:TeamMember).update? %>
              <%= link_to  edit_team_member_path(team_member), class: "text-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
            <% end %>

            <% if policy(:TeamMember).delete? %>
              <%= link_to  delete_member_path(team_member), data: {turbo_method: :delete  , turbo_confirm: 'Are you sure?'}, class: "text-danger" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          </td> 
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/team_members/new.html.erb
<div class="page-wrapper">
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Create member</h3>
        </div>
        <%= form_with(scope: :team_member,local: true,class: "card", url: create_team_member_path,data: { turbo: false }, method: :post) do |f| %>
        
        <div class="card-body">
          <div class="row row-cards">
            <%@team_member.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, :placeholder => "Name" , class: "form-control"%> 
              </div>
            </div>              


            <%@team_member.errors.full_messages_for(:profile).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :profile, class: "form-label" %>
                <%= f.select :profile, options_for_select(profile_dropdown(current_company.id)), { prompt: 'Select a Profile' }, class: 'form-control', id: 'profile-dropdown-team-member' %>
              </div>
            </div>              


            <%@team_member.errors.full_messages_for(:employee_id).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :employee_id,value: "Employee ID", class: "form-label" %>
                <%= f.text_field :employee_id, :placeholder => "employee ID" , class: "form-control" %> 
              </div>
            </div>              
            

            <%@team_member.errors.full_messages_for(:email).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :email, class: "form-label" %>
                <%= f.text_field :email, :placeholder => "email" , class: "form-control" %> 
              </div>
            </div>              
            
            <%@team_member.errors.full_messages_for(:role_id).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :role_id, class: "form-label" %>
                <%= f.select :role_id, options_for_select(role_dropdown), { prompt: 'Select a Role' }, class: 'form-control', id: 'role-dropdown' %>
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:contact_number).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :contact_number, class: "form-label" %>
                <%= f.text_field :contact_number, :placeholder => "contact number" , class: "form-control" %> 
              </div>
            </div>              

            <%@team_member.errors.full_messages_for(:password).each do |message| %>
            <div><%= message %></div>
            <%end%>
            <div class="col-md-5">
              <div class="mb-3">
                <%= f.label :password, class: "form-label" %>
                <%= f.password_field :password, :placeholder => "password" , class: "form-control" %> 
              </div>
            </div>              

            <div class="col-md-5">
              <div class="mb-3">
                <%= hidden_field_tag "team_member[company_id]", current_team_member.company.id%>
              </div>
            </div> 
          </div>
        </div>                 

        
        <div class="card-footer text-end">    
          <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/team_members/show.html.erb
<div class="page-wrapper">
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="">
      <div class="row g-2 align-items-center">
        <div class="col">
          <h2 class="h3 mb-0 text-gray-800">
           Team member Details
         </h2>
       </div>
     </div>
   </div>
 </div>
 <!-- Page body -->
 <div class="table-responsive shadow">
  <table class="table table-bordered table-go">
    <thead>
      <tr>
        <th>Employee ID</th>
        <th>Name</th>
        <th>Role</th>
        <th>Email</th>
        <th>Contact Number</th>
        <th>Profile</th>
      </tr>
    </thead>
    <tbody class="table-tbody">
      <tr>
        <td class="sort-designation_name"><%= @team_member.employee_id %></td>
        <td class="sort-designation_name"><%= @team_member.name %></td>
        <td class="sort-designation_name"><%= @team_member.role.name %></td>
        <td class="sort-designation_name"><%= @team_member.email %></td>
        <td class="sort-designation_name"><%= @team_member.contact_number %></td>
        <td class="sort-designation_name"><%= @team_member.profile %></td>
      </tr>
    </tbody>
  </table>
</div>
</div>
<%= stylesheet_link_tag  "team_members" %>