config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :team_members, controllers: { registrations: 'team_members/registrations' }
  # devise_for :companies
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'home#index'
  resources :departments do
    resources :desingations
  end
  resources :companies do
    resources :permissions, only: %w[index] do
      collection do
        post 'permissions_setter'
      end
    end
  end

  resources :applicants do
    collection do
      get "applicant_profile_data"
    end
    resources :interviews
  end
  resources :team_members
  resources :comments
  resources :profiles
  resources :roles
  resources :subscriptions
  resources :organisation_settings,only:[:index,:new,:edit]
  
  get '/team_members/:id/interviews' => 'interviews#interview_feedback', as: "interview_feedback"

  put 'team_members/:id/feedback_update' => 'interviews#feedback_update', as: 'feedback_update'

  get '/team_members/:id/assigned_interviews' => 'interviews#assigned_interviews', as: 'assigned_interviews'
  get '/interviews/data' =>'interviews#data'
  get '/interviews/show_data' =>'interviews#show_data'
  post '/team_members_create' => 'team_members#create_member', as: 'create_team_member'
  delete '/team_members/:id' => 'team_members#destroy', as: 'delete_member'

  resources :bulk_uploads, only: %w[index new create]

  get '/team_details/' => 'team_members#team_details', as: 'team_details'

  get '/applicant_upload_bulk/new' => 'applicants#new_bulk_upload', as: 'bulk_upload_applicant'
  post '/applicant_upload_bulk/new' => 'bulk_uploads#create'
  post '/applicant_upload_bulk/data' => 'applicants#applicant_data_mapping', as: 'bulk_upload_data'
  post '/applicant_upload_bulk/rejected' => 'applicants#send_csv'
  get  "/saml/init" => "saml#init"
  post "/saml/consume" => "saml#consume"
  post "/saml/create_sso_organization" => "saml#create_sso_organization"
  post "/saml/create_user" => "saml#create_user"
  get  "sign-in" => "saml#sign", as: :saml_sign
  delete  "saml/logout" => "saml#logout"
  post '/create_organisation' =>'organisation_settings#create_organisation'
  get '/home/graph_show' => 'home#graph_show'
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :team_members, dependent: :destroy
	has_many :permissions, dependent: :destroy

  scope :admin, -> { where(name: "Admin") }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_team_member!
  before_action :load_resource, only: %w(show edit update destroy)
  before_action :authorize_section, only: %i[index show new create edit update destroy]

  def index
    @roles = Role.where(company_id: current_company.id)
	end

	def show
	end

	def new
		@profile = Role.new
	end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path, notice: "role created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @role.update(role_params)
      redirect_to role_path(@role), notice: "role updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_path, notice: "role is removed!"
  end

  private

  def authorize_section
    authorize :Role
  end

  def role_params
    params.permit(:id, :name, :company_id, :create_by)
  end

  def load_resource
  	@role = Role.find params[:id]
  end

end

app/views/roles/_form.html.erb
    <!-- Card Body -->
    <%= form_with model: @role, local:true, url: @url, class: "card" do |form| %>
      <div class="card-body">
        <div class="row row-cards">
          <div class="col-md-5">
            <div class="mb-3">
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control", placeholder: "Enter Role Name" %>
              <%= form.hidden_field :company_id, value: current_company.id %>
              <%= form.hidden_field :create_by, value: current_team_member.name %>
            </div>
          </div>
        </div>
      </div>

      <div class="card-footer text-end">
        <%= form.submit class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" do %>
          <i class="fas fa-plus fa-sm text-white-50"></i>
        <% end %>
      </div>
    <% end %>

app/views/roles/edit.html.erb
<div class="container-fluid">
	<div class="card shadow mb-4">
		<!-- Card Header - Dropdown -->
		<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
			<h6 class="m-0 font-weight-bold text-primary">Edit Role</h6>
		</div>
    <%= render "form"%>
	</div>
</div>

app/views/roles/index.html.erb
<div class="container-fluid">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Roles</h1>
    <%if policy(:Role).create?%>
      <%= link_to new_role_path, class: "d-none d-sm-inline-block btn btn-sm btn-primary btn-icon-split shadow-sm" do %>
        <span class="icon text-white-50">
          <i class="fas fa-user-plus fa-sm"></i>
        </span>
        <span class="text">Create Role</span>
      <% end %>
    <%end%>
  </div>

  <div class="table-responsive shadow">
    <table class="table table-bordered table-go">
      <thead>
        <tr>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody class="table-tbody">
         <% @roles.each do |role| %>
        <tr>
          <td class="sort-designation_name"><%= role.name %></td>
          <td class="actions">
            <%if policy(:Role).read?%>
              <%= link_to role_path(role.id) do %>
                <i class="fa fa-eye"></i>
              <% end %>
            <% end %>
            <%if policy(:Role).update?%>
              <%= link_to  "/roles/#{role.id}/edit", class: "text-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
            <% end %>
            <%if policy(:Role).delete?%>
              <%= link_to  "/roles/#{role.id}" , data: {turbo_method: :delete  , turbo_confirm: 'Are you sure?'}, class: "text-danger" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/roles/new.html.erb
<div class="container-fluid">
	<div class="card shadow mb-4">
		<!-- Card Header - Dropdown -->
		<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
			<h6 class="m-0 font-weight-bold text-primary">Create new Role</h6>
		</div>
    <% @url = roles_url %>
		<%= render "form" %>
	</div>
</div>

app/views/roles/show.html.erb
<div class="page-wrapper">
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="">
      <div class="row g-2 align-items-center">
        <div class="col">
          <h2 class="h3 mb-0 text-gray-800">
           Role Details
          </h2>
        </div>
      </div>
    </div>
  </div>
  <!-- Page body -->
  <div class="table-responsive shadow">
    <table class="table table-bordered table-go">
      <thead>
        <tr>
          <th>Role</th>
          <th>Role Created By</th>
        </tr>
      </thead>
      <tbody class="table-tbody">
        <tr>
          <td class="sort-designation_name"><%= @role.name %></td>
          <td class="sort-designation_name"><%= @role.create_by %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<%= stylesheet_link_tag  "team_members" %>